# Generated by Django 5.1 on 2024-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
