# Generated by Django 5.1 on 2024-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
