# Generated by Django 5.1.3 on 2024-11-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
            ],
        ),
    ]
