# Generated by Django 5.1.3 on 2024-11-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
